use v5.42;
use experimental 'class';

class API::hCaptcha v0.1.0;

use JSON;
use REST::Client;
use URI;

field $client;
field $error   :reader = undef;
field $secret  :param;

ADJUST {
    $client = REST::Client->new({
            host => 'https://api.hcaptcha.com',
        });

    $client->addHeader(
            'Content-type' => 'application/x-www-form-urlencoded'
        );
}

method verify ($token, $ip = undef)
{
    # Build body query
    my $body = do {
        my %data = (
            secret => $secret,
            response => $token,
        );
        $data{remoteip} = $ip if defined $ip;
        my $u = URI->new('http:');
        $u->query_form(%data);
        $u->query;
    };

    # Call the API
    $client->POST('/siteverify', $body);

    # Check if we had a valid response
    my $code = $client->responseCode;
    my $res;

    die "hCaptcha connection returned $code\n"
        if ($code < 200 || $code >= 300);

    try {
        $res = decode_json $client->responseContent;
    } catch ($e) {
        die "Failed to parse hCaptcha response\n";
    }

    die "Invalid API response\n" unless exists $res->{success};

    # Assert result
    if ($res->{success}) {
        $error = undef;
        return true;
    }

    $error = join ', ', $res->{'error-codes'}->@*;
    return false;
}

__END__

=head1 NAME

API::hCaptcha -- Verify hCaptcha response tokens

=head1 SYNOPSIS

    use API::hCaptcha;

    my $hCaptcha = API::hCaptcha->new(secret => 'secret');

    if ($hCaptcha->verify($token, $remote_ip)) {
        say 'challenge accepted';
    } else {
        warn 'hCaptcha rejected the response: ' . $hCaptcha->error;
    }

=head1 DESCRIPTION

C<API::hCaptcha> is a small client for the hCaptcha C</siteverify>
endpoint. It posts a visitor response token together with your secret
key and returns a boolean result indicating whether hCaptcha accepted
the challenge.

Failed challenge verification returns false and stores the hCaptcha
error codes in C<error>. Transport failures, invalid JSON responses, and
malformed API responses throw exceptions because they indicate that the
verification request itself could not be trusted.

=head1 METHODS

=head2 new

    method new (secret => $secret)

Creates a new hCaptcha API client. Requires the hCaptcha secret key for
the site or application that issued the challenge.

=head2 verify

    method verify ($token, $ip = undef)

Verifies a response token with hCaptcha.

=over 8

=item C<$token>

The response token generated by the hCaptcha widget or integration.

=item C<$ip>

Optional visitor IP address to send as C<remoteip>.

=back

Returns true when hCaptcha accepts the challenge. Returns false when
hCaptcha rejects it, in which case C<error> contains the reported error
codes joined by a comma and a space.

Dies if the HTTP response status is outside the 2xx range, if the
response body cannot be parsed as JSON, or if the decoded response does
not include a C<success> field.

=head2 error

    method error

Returns the last hCaptcha error string produced by C<verify>, or C<undef>
after a successful verification. The value is only meaningful when
C<verify> returns false.

=head1 AUTHOR

Cesar Tessarin, E<lt>cesar@tessarin.com.brE<gt>.

Written in 2026.
